from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from scripts.keepalive_backup import (
    postgres_environment,
    validated_r2_configuration,
    verified_postgres_url,
)
from scripts.write_acceptance_report import main as write_acceptance_report
from services.api.database import (
    verified_postgres_dsn as verified_runtime_postgres_dsn,
)

VERIFIED_DSN = (
    "postgresql://health:secret@db.example.test/odisha"
    "?sslmode=verify-full&sslrootcert=system"
)


def test_database_maintenance_requires_authenticated_tls() -> None:
    assert verified_postgres_url(VERIFIED_DSN) == VERIFIED_DSN
    environment = postgres_environment(VERIFIED_DSN)
    assert environment["PGSSLMODE"] == "verify-full"
    assert environment["PGSSLROOTCERT"] == "system"
    assert environment["PGHOST"] == "db.example.test"

    for insecure in (
        "postgresql://health:secret@db.example.test/odisha",
        "postgresql://health:secret@db.example.test/odisha?sslmode=require",
        "postgresql://health:secret@db.example.test/odisha?sslmode=verify-full",
    ):
        with pytest.raises(ValueError):
            verified_postgres_url(insecure)

    assert verified_runtime_postgres_dsn(VERIFIED_DSN) == VERIFIED_DSN
    assert verified_runtime_postgres_dsn("postgresql://u:p@127.0.0.1:5432/test") == (
        "postgresql://u:p@127.0.0.1:5432/test"
    )
    with pytest.raises(ValueError, match="sslmode=verify-full"):
        verified_runtime_postgres_dsn("postgresql://u:p@db.example.test/test")


def test_backup_destination_is_restricted_to_account_scoped_cloudflare_r2() -> None:
    values = {
        "R2_ENDPOINT_URL": "https://0123456789abcdef0123456789abcdef.r2.cloudflarestorage.com",
        "R2_ACCESS_KEY_ID": "access",
        "R2_SECRET_ACCESS_KEY": "secret",
        "R2_BUCKET": "odisha-health-backups",
    }
    assert validated_r2_configuration(values)["bucket"] == "odisha-health-backups"
    for endpoint in (
        "http://0123456789abcdef0123456789abcdef.r2.cloudflarestorage.com",
        "https://receiver.example",
        "https://0123456789abcdef0123456789abcdef.r2.cloudflarestorage.com/upload",
    ):
        with pytest.raises(ValueError):
            validated_r2_configuration({**values, "R2_ENDPOINT_URL": endpoint})


def test_scheduled_collector_destination_is_admin_secret_not_repo_variable() -> None:
    workflow = yaml.safe_load(
        Path(".github/workflows/source-collector.yml").read_text(encoding="utf-8")
    )
    rendered = str(workflow)
    assert "secrets.COLLECTOR_API_BASE_URL" in rendered
    assert "vars.PUBLIC_API_BASE_URL" not in rendered

    cli = subprocess.run(  # noqa: S603 - interpreter and checked-in script are fixed
        [sys.executable, "scripts/trigger_collector.py", "--help"],
        capture_output=True,
        check=False,
        text=True,
        timeout=10,
    )
    assert cli.returncode == 0, cli.stderr
    assert "--deadline-seconds" in cli.stdout


def test_local_compose_ports_are_loopback_only() -> None:
    compose = yaml.safe_load(Path("docker-compose.yml").read_text(encoding="utf-8"))
    assert compose["services"]["api"]["ports"] == ["127.0.0.1:8000:8000"]
    assert compose["services"]["web"]["ports"] == ["127.0.0.1:5173:4173"]


def test_acceptance_report_cannot_be_minted_outside_verify_chain(
    monkeypatch,
) -> None:
    monkeypatch.delenv("ACCEPTANCE_PREREQUISITES", raising=False)
    with pytest.raises(SystemExit, match="must be generated by `make verify`"):
        write_acceptance_report()
