"""Evidence-grounded assistant: semantic retrieval + local generative answering.

The assistant is two layers that must not be confused with each other.

*Deterministic guardrails* decide what may be answered at all.  Current
environmental outlooks, case-count boundaries, clinical questions and
ambiguous scopes are handled by reviewed policy code; a language model is not
allowed to invent a forecast, a count, or an operational alert.

*Learned components* answer the questions that evidence can support.  Retrieval
is cross-lingual sentence embeddings (multilingual-E5) over the collected
records, so an English question finds Odia and Hindi evidence.  A live record
retains no source text, so what is embedded for it is its structured
provenance -- disease, district in three scripts, registered document title,
language, date -- and each answer reports which of the two it ranked.  The
answer is generated by a local Qwen2.5-1.5B (llama.cpp, CPU) from a prompt that
contains only the retrieved records, and the whole reply is rendered in the
caller's language by the local IndicTrans2 translator.

Two release rules are enforced here rather than left to the model:

* live source text is never placed in the prompt.  Live rows enter the prompt as
  provenance metadata only, because the platform does not publish live text
  while multilingual PERSON redaction recall is unvalidated.  Synthetic fixture
  text is inspectable and is passed in full;
* every model-backed capability degrades to the previous deterministic summary
  when its model is not downloaded, and says so in ``capabilities``.
"""

from __future__ import annotations

import functools
import re
from dataclasses import dataclass
from typing import Any, Literal

from packages.contracts.api import LIVE_EVIDENCE_PLACEHOLDER, LIVE_EVIDENCE_REDACTION_STATE
from packages.nlp import answer as generation
from packages.nlp import models as nlp_models
from packages.nlp import retrieval
from packages.nlp import translate as translation
from packages.nlp.glossary import district_display_name, district_terms
from packages.nlp.retrieval import EvidenceRecord, RankedRecord
from workers.ingestion.diseases import DiseaseLexicon
from workers.ingestion.geography import DistrictGazetteer
from workers.ingestion.language import route_unicode

from .database import Database

Intent = Literal[
    "evidence_search",
    "candidate_alerts",
    "verified_events",
    "forecast_request",
    "incidence_request",
    "data_audit",
    "clinical_advice_request",
]

#: Records handed to the generator.  Kept small because CPU generation cost is
#: dominated by prompt length.
MAXIMUM_PROMPT_RECORDS = 4

FORECAST_TERMS = (
    "forecast",
    "predict",
    "prediction",
    "likelihood",
    "risk next",
    "अगले",
    "पूर्वानुमान",
    "संभावना",
    "ପୂର୍ବାନୁମାନ",
    "ସମ୍ଭାବନା",
)
OUTLOOK_TERMS = (
    "outlook",
    "environmental outlook",
    "weather outlook",
    "environmental conditions",
    "weather-related risk",
    "मौसम का पूर्वानुमान",
    "पर्यावरणीय जोखिम",
    "ପରିବେଶ ଦୃଷ୍ଟିକୋଣ",
    "ପାଣିପାଗ ଦୃଷ୍ଟିକୋଣ",
)
FUTURE_TERMS = (
    "next week",
    "next month",
    "next 3 months",
    "next three months",
    "coming week",
    "coming month",
    "in advance",
    "12 week",
    "three-month",
    "will there be",
    "will increase",
    "will spread",
    "will occur",
    "अगले",
    "आगामी",
    "भविष्य",
    "होगा",
    "फैलेगा",
    "ଆଗାମୀ",
    "ପରବର୍ତ୍ତୀ",
    "ଭବିଷ୍ୟତ",
    "ହେବ",
    "ବ୍ୟାପିବ",
)
OUTBREAK_TERMS = (
    "outbreak",
    "epidemic",
    "surge",
    "प्रकोप",
    "महामारी",
    "ପ୍ରକୋପ",
    "ମହାମାରୀ",
)
INCIDENCE_TERMS = (
    "how many cases",
    "case rate",
    "incidence",
    "burden",
    "कितने मामले",
    "मामलों की संख्या",
    "କେତେ ମାମଲା",
    "ରୋଗ ହାର",
)
#: Distribution phrasings that are self-quantifying. "Show the malaria heatmap"
#: and "rank the districts for malaria" ask about the disease itself, so -- like
#: a trend question -- they need no separate counted noun to be a question about
#: official statistics rather than about published documents.
DISTRIBUTION_TERMS = (
    "rank",
    "heatmap",
    "pattern",
    "across the state",
)
#: Comparison and trend phrasings. These ask about official statistics just as
#: much as "how many cases" does, but they name two districts or a span of years
#: rather than one of each, so they used to fall through to the media-evidence
#: path and be refused as ambiguous while the official annual table sat unread.
COMPARISON_TERMS = (
    "more cases",
    "fewer cases",
    "higher",
    "lower",
    "compare",
    "compared to",
    "which district",
    "worst",
    "highest",
    "lowest",
    "more malaria",
    # Ranking, mapping and distribution phrasings. "Rank the districts by malaria
    # burden" and "show the malaria heatmap" are official-statistics questions
    # that were answered with counts of published documents, which is a different
    # quantity entirely.
    "top",
    "most",
    *DISTRIBUTION_TERMS,
    "ज्यादा मामले",
    "तुलना",
    "कौन सा जिला",
    "ଅଧିକ ମାମଲା",
    "ତୁଳନା",
    "କେଉଁ ଜିଲ୍ଲା",
)
#: Phrasings that ask which districts lead, answered by ordering the official
#: table.  "Lowest" and "fewest" are deliberately absent: they would need the
#: opposite ordering, and returning the highest for them would be a wrong answer.
RANKING_TERMS = (
    *DISTRIBUTION_TERMS,
    "top",
    "most",
    "highest",
    "worst",
    "which district",
    "कौन सा जिला",
    "କେଉଁ ଜିଲ୍ଲା",
)
#: A counted quantity, which the official annual table can report.
STATISTIC_NOUNS = (
    "case",
    "cases",
    "incidence",
    "api",
    "burden",
    "death",
    "deaths",
    "positivity",
    "मामले",
    "मामलों",
    "ମାମଲା",
)
#: Published-record vocabulary. These questions belong to the media-evidence
#: path even when phrased as a comparison, because the quantity is documents.
EVIDENCE_NOUNS = (
    "evidence",
    "published",
    "coverage",
    "article",
    "news",
    "report about",
    "प्रमाण",
    "समाचार",
    "ପ୍ରମାଣ",
    "ଖବର",
)
TREND_TERMS = (
    "gone up",
    "gone down",
    "increased",
    "decreased",
    "rising",
    "falling",
    "trend",
    "over the years",
    "since 20",
    # Year-to-year phrasings that never use a trend verb: "how did malaria change
    # between 2015 and 2024", "malaria from 2019 compared with 2024".
    "change between",
    "how did",
    "from 20",
    "compared with 20",
    "बढ़ा",
    "घटा",
    "रुझान",
    "ବୃଦ୍ଧି",
    "ହ୍ରାସ",
    "ଧାରା",
)
ALERT_TERMS = ("alert", "warning", "signal", "चेतावनी", "ସତର୍କ", "ସଙ୍କେତ")
VERIFIED_TERMS = ("verified", "confirmed event", "सत्यापित", "ଯାଞ୍ଚ")
AUDIT_TERMS = ("epiclim", "training data", "historical data", "dataset", "ଡାଟା", "डेटासेट")
CLINICAL_ADVICE_TERMS = (
    "what treatment",
    "which treatment",
    "what medicine",
    "which medicine",
    "what should i take",
    "what dose",
    "diagnose me",
    "इलाज",
    "दवा",
    "खुराक",
    "क्या करूँ",
    "ଚିକିତ୍ସା",
    "ଔଷଧ",
    "ମୁଁ କଣ କରିବି",
)

#: Every phrase that carries an intent of its own.  A follow-up that contains
#: none of them ("What about Koraput?") is a scope change, not a new question.
INTENT_TERMS: tuple[str, ...] = (
    *FORECAST_TERMS,
    *OUTLOOK_TERMS,
    *FUTURE_TERMS,
    *OUTBREAK_TERMS,
    *INCIDENCE_TERMS,
    *COMPARISON_TERMS,
    *DISTRIBUTION_TERMS,
    *STATISTIC_NOUNS,
    *EVIDENCE_NOUNS,
    *TREND_TERMS,
    *ALERT_TERMS,
    *VERIFIED_TERMS,
    *AUDIT_TERMS,
    *CLINICAL_ADVICE_TERMS,
    "how many",
    "epiclim",
)

#: A year the question names, within the range the official reports cover.
_YEAR_IN_QUESTION = re.compile(r"\b(20[0-2]\d)\b")

#: A capitalised token used as a place: "cases in Bhopal", "Bhopal district".
#: Latin script only -- Hindi and Odia do not capitalise, so a place written in
#: those scripts is recognised through the gazetteer or not at all.
_PLACE_PHRASE = re.compile(
    r"\b(?:in|at|for|from|near|around|about|across)\s+"
    r"(?!the\b)([A-Z][A-Za-z]{2,}(?:\s+[A-Z][A-Za-z]{2,})?)"
    r"|\b([A-Z][A-Za-z]{2,})\s+(?:district|District|zilla|Zilla)\b"
)
#: Capitalised words that follow a preposition but are not places.  A sentence
#: opens with a capital, so interrogatives and determiners land here too --
#: "Which district ..." must not be read as a district called "Which".
_NOT_A_PLACE = frozenset(
    word.casefold()
    for word in (
        "Which",
        "What",
        "Whose",
        "Where",
        "When",
        "This",
        "That",
        "These",
        "Those",
        "Each",
        "Every",
        "Any",
        "All",
        "The",
        "Our",
        "Their",
        "Its",
        "Some",
        "Both",
        "Other",
        "Another",
        "Show",
        "Give",
        "Tell",
        "Compare",
        "Odisha",
        "Orissa",
        "India",
        "Indian",
        "Bharat",
        "State",
        "District",
        "Districts",
        "EpiClim",
        "IDSP",
        "HMIS",
        "NCVBDC",
        "IMD",
        "ECMWF",
        "NASA",
        "WHO",
        "ICMR",
        "MoHFW",
        "API",
        "English",
        "Hindi",
        "Odia",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    )
)

AMBIGUOUS_ANSWER = (
    "The question resolves to more than one district or disease. "
    "Choose one explicit scope; the assistant will not silently select "
    "the first match."
)
CLINICAL_ANSWER = (
    "This evidence assistant cannot diagnose a person, choose a medicine "
    "or recommend a dose. Contact a qualified healthcare professional. "
    "For severe symptoms or an emergency, seek the nearest emergency "
    "medical service immediately."
)
FORECAST_ANSWER = (
    "The environmental early-warning layer is temporarily unavailable. "
    "No substitute score was generated."
)
INCIDENCE_ANSWER = (
    "Published-source counts cannot answer case incidence or burden. "
    "Authorised routine surveillance counts, reporting completeness and "
    "denominators are unavailable in this deployment."
)
NOT_INCIDENCE_CAVEAT = "These are counts of published evidence records, not case counts."
OUTSIDE_ODISHA_ANSWER = (
    "This platform holds records for the 30 districts of Odisha only, and "
    "{place} is not one of them. No Odisha district was substituted for it. "
    "Ask again naming an Odisha district."
)
AUDIT_ANSWER = (
    "The frozen EpiClim audit contains 358 Odisha rows across 2009–2022, "
    "including 2 dengue rows. Nationally, 2,517 of 8,985 rows have a "
    "date-derived ISO-week mismatch greater than one week after "
    "year-boundary correction. It is ineligible "
    "for Odisha district-week count forecasting."
)


#: Language names as an embedding model reads them; "or" is not a word.
_LANGUAGE_NAMES = {"en": "English", "hi": "Hindi", "or": "Odia"}


@functools.lru_cache(maxsize=1)
def _source_titles() -> dict[str, str]:
    """Registered document titles by source id.

    A registry title ("Odisha Health and Family Welfare circulars (Odia)") is
    reviewed platform metadata, not crawled text, so it is safe to embed where
    the document body is not, and it is the only content-bearing string a live
    row has.
    """

    try:
        from workers.ingestion.registry import load_registry  # noqa: PLC0415

        return {source.id: source.name for source in load_registry().sources}
    except Exception:  # noqa: BLE001 - retrieval degrades, it never fails a request
        return {}


@dataclass(slots=True)
class EvidenceAgent:
    database: Database
    gazetteer: DistrictGazetteer
    diseases: DiseaseLexicon

    @classmethod
    def create(cls, database: Database) -> EvidenceAgent:
        return cls(
            database=database,
            gazetteer=DistrictGazetteer.load(),
            diseases=DiseaseLexicon.load(),
        )

    # ------------------------------------------------------------------
    # public entry point
    # ------------------------------------------------------------------
    def answer(
        self,
        question: str,
        *,
        district_id: str | None,
        disease: str | None,
        maximum_evidence: int,
        target_language: str | None = None,
        history: list[dict[str, str]] | None = None,
    ) -> dict[str, Any]:
        detected = route_unicode(question).value
        question_language = detected if detected in {"en", "hi", "or"} else "en"
        requested = (target_language or "").strip().lower()
        answer_language = requested if requested in {"en", "hi", "or"} else question_language

        english_question = self._to_english(question, question_language)
        resolved_districts = self.gazetteer.resolve(question)
        resolved_diseases = self.diseases.find(question)
        if english_question != question:
            # A translated question exposes district and disease names the native
            # gazetteer spelling may have missed (and vice versa); both are used.
            resolved_districts = resolved_districts + self.gazetteer.resolve(english_question)
            resolved_diseases = tuple(resolved_diseases) + tuple(
                self.diseases.find(english_question)
            )
        distinct_districts = tuple(dict.fromkeys(match.district_id for match in resolved_districts))
        distinct_diseases = tuple(dict.fromkeys(resolved_diseases))

        # Follow-up context is intentionally narrow. Only prior USER questions
        # may provide a missing district or disease; generated assistant text is
        # never fed back as a fact. The newest unambiguous user turn wins.
        prior_user_turns = [
            str(turn.get("content", "")).strip()
            for turn in (history or [])
            if turn.get("role") == "user" and str(turn.get("content", "")).strip()
        ]
        historical_district: str | None = None
        historical_disease: str | None = None
        for prior in reversed(prior_user_turns):
            if historical_district is None:
                matches = tuple(
                    dict.fromkeys(match.district_id for match in self.gazetteer.resolve(prior))
                )
                if len(matches) == 1:
                    historical_district = matches[0]
            if historical_disease is None:
                matches = tuple(dict.fromkeys(self.diseases.find(prior)))
                if len(matches) == 1:
                    historical_disease = matches[0]
            if historical_district is not None and historical_disease is not None:
                break
        selected_district = district_id or (
            distinct_districts[0] if len(distinct_districts) == 1 else historical_district
        )
        selected_disease = disease or (
            distinct_diseases[0] if len(distinct_diseases) == 1 else historical_disease
        )
        intent = self._intent(
            question.casefold(),
            has_disease=bool(disease or distinct_diseases),
        )
        if intent == "evidence_search" and english_question != question:
            intent = self._intent(
                english_question.casefold(),
                has_disease=bool(disease or distinct_diseases),
            )
        # A follow-up carries scope but usually not intent: "What about Koraput?"
        # after a forecast question is still a forecast question, and answering it
        # with an evidence search silently changed the subject.  Intent is
        # inherited only when the current question states none of its own.
        inherited_intent = False
        if (
            intent == "evidence_search"
            and prior_user_turns
            and not self._carries_intent_terms(question)
            and not self._carries_intent_terms(english_question)
        ):
            for prior in reversed(prior_user_turns):
                previous = self._intent(
                    prior.casefold(),
                    has_disease=bool(self.diseases.find(prior)) or bool(selected_disease),
                )
                if previous != "evidence_search":
                    intent = previous
                    inherited_intent = True
                    break
        scope = {
            "district_id": selected_district,
            "disease": selected_disease,
            "question_language": question_language,
            "conversation_context_used": bool(
                prior_user_turns
                and (
                    historical_district is not None
                    or historical_disease is not None
                    or inherited_intent
                )
            ),
            "intent_inherited_from_history": inherited_intent,
        }

        ambiguous_district = district_id is None and len(distinct_districts) > 1
        ambiguous_disease = disease is None and len(distinct_diseases) > 1
        # Naming two districts is only ambiguous when the answer must pick one.
        # An official-statistics question can report both from the annual table,
        # so refusing it there would hide data the platform already holds. A
        # second disease stays ambiguous: the official series is per-disease.
        if intent == "incidence_request" and not ambiguous_disease:
            ambiguous_district = False
        if ambiguous_district or ambiguous_disease:
            return self._deterministic(
                intent=intent,
                answer_state="ambiguous_scope",
                english_answer=AMBIGUOUS_ANSWER,
                scope=scope,
                reason_codes=["AMBIGUOUS_QUERY_SCOPE"],
                answer_language=answer_language,
                question_language=question_language,
                extra={
                    "scope_candidates": {
                        "district_ids": list(distinct_districts),
                        "diseases": list(distinct_diseases),
                    }
                },
            )

        if intent == "clinical_advice_request":
            return self._deterministic(
                intent=intent,
                answer_state="out_of_scope_clinical",
                english_answer=CLINICAL_ANSWER,
                scope=scope,
                reason_codes=["CLINICAL_ADVICE_OUT_OF_SCOPE"],
                answer_language=answer_language,
                question_language=question_language,
            )

        # A place the gazetteer cannot resolve is not a licence to answer from
        # whichever Odisha rows happen to match the disease: "malaria cases in
        # Bhopal" was answered with Odisha records and read as a Bhopal figure.
        if district_id is None and not distinct_districts:
            outside = self._place_outside_odisha(question, english_question)
            if outside is not None:
                return self._deterministic(
                    intent=intent,
                    answer_state="district_not_in_odisha",
                    english_answer=OUTSIDE_ODISHA_ANSWER.format(place=outside),
                    scope=scope,
                    reason_codes=["PLACE_OUTSIDE_ODISHA_COVERAGE"],
                    answer_language=answer_language,
                    question_language=question_language,
                    extra={"unresolved_place": outside},
                )
        if intent == "forecast_request":
            return self._forecast_outlook(
                scope=scope,
                english_question=english_question,
                selected_district=selected_district,
                selected_disease=selected_disease,
                answer_language=answer_language,
                question_language=question_language,
            )
        if intent == "incidence_request":
            public_observation = self._public_malaria_observation(
                scope=scope,
                selected_district=selected_district,
                selected_disease=selected_disease,
                answer_language=answer_language,
                question_language=question_language,
                comparison_districts=list(distinct_districts),
                wants_trend=any(
                    term in english_question.casefold() for term in TREND_TERMS
                ),
                wants_ranking=any(
                    term in english_question.casefold() for term in RANKING_TERMS
                ),
                requested_years=self._requested_years(english_question),
            )
            if public_observation is not None:
                return public_observation
            return self._deterministic(
                intent=intent,
                answer_state="not_observable_from_public_sources",
                english_answer=INCIDENCE_ANSWER,
                scope=scope,
                reason_codes=["NOT_INCIDENCE", "AUTHORISED_SURVEILLANCE_NOT_SUPPLIED"],
                answer_language=answer_language,
                question_language=question_language,
            )
        if intent == "data_audit":
            return self._deterministic(
                intent=intent,
                answer_state="audited_public_catalogue",
                english_answer=AUDIT_ANSWER,
                scope=scope,
                reason_codes=["POSITIVE_ONLY_CATALOGUE", "TARGET_SERIES_INELIGIBLE"],
                answer_language=answer_language,
                question_language=question_language,
            )

        if intent == "verified_events":
            events = self.database.list_verified_events(
                limit=maximum_evidence,
                district_id=selected_district,
                disease=selected_disease,
            )
            english = (
                f"Found {len(events)} active reviewer-verified event record(s). "
                "Reviewer verification is not the same as official surveillance."
            )
            payload = self._deterministic(
                intent=intent,
                answer_state="records_returned" if events else "insufficient_evidence",
                english_answer=english,
                scope=scope,
                reason_codes=[] if events else ["NO_VERIFIED_EVENT_IN_CURRENT_STORE"],
                answer_language=answer_language,
                question_language=question_language,
            )
            payload["evidence"] = events
            payload["is_synthetic"] = any(bool(item.get("is_fixture")) for item in events)
            return payload

        return self._evidence_answer(
            question=question,
            english_question=english_question,
            prior_user_turns=prior_user_turns,
            intent=intent,
            scope=scope,
            selected_district=selected_district,
            selected_disease=selected_disease,
            maximum_evidence=maximum_evidence,
            question_language=question_language,
            answer_language=answer_language,
        )

    # ------------------------------------------------------------------
    # retrieval + generation
    # ------------------------------------------------------------------
    def _forecast_outlook(
        self,
        *,
        scope: dict[str, Any],
        english_question: str,
        selected_district: str | None,
        selected_disease: str | None,
        answer_language: str,
        question_language: str,
    ) -> dict[str, Any]:
        """Answer from a qualified disease model, otherwise from environmental context.

        The authorised model is attempted only when the question resolves to a
        disease. A missing/unqualified/stale model falls through to the current
        environmental priority layer, preserving a useful answer without
        relabelling weather context as disease probability.
        """

        horizon = self._forecast_horizon(english_question)
        if selected_disease:
            try:
                from packages.forecasting.operational import current_probability_map

                forecast = current_probability_map(
                    disease=selected_disease,
                    horizon_weeks=horizon,
                )
            except Exception:  # noqa: BLE001 - environmental fallback is the public contract
                forecast = None
            if forecast and forecast.get("status") == "published":
                districts = list(forecast.get("districts") or [])
                district_row = next(
                    (row for row in districts if row.get("district_id") == selected_district),
                    None,
                )
                if district_row is not None:
                    probability = float(district_row["probability_threshold_exceedance"])
                    threshold = float(district_row["outbreak_threshold_per_100k"])
                    completeness = float(district_row["latest_case_volume_completeness"])
                    district_name = str(selected_district).removeprefix("OD-DIST-")
                    english = (
                        f"For {district_name.replace('-', ' ').title()}, the qualified "
                        f"{horizon}-week {selected_disease.replace('_', ' ')} model gives "
                        f"a {probability * 100:.1f}% probability of crossing the registered "
                        f"threshold of {threshold:g} cases per 100,000. The latest case-volume "
                        f"completeness is {completeness * 100:.0f}%. Review the model drivers "
                        "and local evidence before escalation."
                    )
                    answer_rows = [district_row]
                else:
                    ranked = sorted(
                        districts,
                        key=lambda row: float(row["probability_threshold_exceedance"]),
                        reverse=True,
                    )[:5]
                    summary = ", ".join(
                        f"{self._district_display(str(row['district_id']))} "
                        f"{float(row['probability_threshold_exceedance']) * 100:.1f}%"
                        for row in ranked
                    )
                    english = (
                        f"The highest qualified {horizon}-week "
                        f"{selected_disease.replace('_', ' ')} "
                        f"threshold-exceedance probabilities are {summary}. Each value uses the "
                        "registered disease threshold, current environment and authorised "
                        "as-of surveillance history."
                    )
                    answer_rows = ranked
                payload = self._deterministic(
                    intent="forecast_request",
                    answer_state="forecast_probability",
                    english_answer=english,
                    scope=scope,
                    reason_codes=[
                        "QUALIFIED_OPERATIONAL_FORECAST",
                        "HUMAN_VERIFICATION_REQUIRED",
                    ],
                    answer_language=answer_language,
                    question_language=question_language,
                    generation_mode="policy_response",
                )
                payload["forecast"] = {
                    "issue_week": forecast.get("issue_week"),
                    "horizon_weeks": horizon,
                    "disease": selected_disease,
                    "quantity": forecast.get("quantity"),
                    "districts": answer_rows,
                    "is_synthetic": False,
                }
                return payload

        # Public-data predictive analysis is a separate, deliberately narrower
        # contract.  It is useful for malaria planning questions even when the
        # authorised routine-surveillance model is unavailable: the target is
        # elevated monthly HMIS microscopy positivity, not an outbreak.  The
        # serving artefact is selected strictly by rolling-origin Brier score.
        if selected_disease == "malaria":
            public = self._public_malaria_outlook(
                scope=scope,
                english_question=english_question,
                selected_district=selected_district,
                answer_language=answer_language,
                question_language=question_language,
            )
            if public is not None:
                return public

        try:
            from packages.forecasting.current_conditions import current_conditions_map

            layer = current_conditions_map()
        except Exception:  # noqa: BLE001 - typed fallback is the public contract
            return self._deterministic(
                intent="forecast_request",
                answer_state="insufficient_evidence",
                english_answer=FORECAST_ANSWER,
                scope=scope,
                reason_codes=["CURRENT_ENVIRONMENTAL_LAYER_UNAVAILABLE"],
                answer_language=answer_language,
                question_language=question_language,
            )

        observed = [
            row
            for row in layer.get("districts", [])
            if row.get("status") == "observed"
            and isinstance(row.get("suitability_percentile"), (int, float))
        ]
        district_row = next(
            (row for row in observed if row.get("district_id") == selected_district),
            None,
        )
        disease_label = (selected_disease or "public-health events").replace("_", " ")
        if selected_district and district_row is None:
            english = (
                f"No current environmental index is available for {selected_district}. "
                "The system did not substitute a neighbouring district or a statewide average."
            )
            payload = self._deterministic(
                intent="forecast_request",
                answer_state="insufficient_evidence",
                english_answer=english,
                scope=scope,
                reason_codes=["DISTRICT_ENVIRONMENTAL_WINDOW_INCOMPLETE"],
                answer_language=answer_language,
                question_language=question_language,
            )
            payload["outlook"] = {"as_of": layer.get("as_of"), "district": None}
            return payload

        if district_row is not None:
            name = str(district_row.get("canonical_name") or selected_district)
            percentile = float(district_row["suitability_percentile"])
            band = str(district_row.get("band") or "unclassified").replace("_", " ")
            drivers = [
                str(item.get("feature", "")).replace("_", " ")
                for item in district_row.get("top_drivers", [])[:3]
                if isinstance(item, dict) and item.get("feature")
            ]
            driver_text = ", ".join(drivers) or "the available weather features"
            warning = str(
                district_row.get("imd_peak_warning_next_5_days") or "not reported"
            ).replace("_", " ")
            english = (
                f"For {name}, the current environmental early-warning index is at the "
                f"{percentile:.1f} percentile of that district's historical seasonal "
                f"conditions ({band}) for {disease_label}. The main drivers are "
                f"{driver_text}; the five-day IMD warning level is {warning}. Use this "
                "to prioritise evidence review and field verification."
            )
            outlook_rows = [district_row]
        else:
            ranked = sorted(
                observed,
                key=lambda row: float(row["suitability_percentile"]),
                reverse=True,
            )[:5]
            summary = ", ".join(
                f"{row.get('canonical_name')} {float(row['suitability_percentile']):.1f}"
                for row in ranked
            )
            english = (
                "The districts with the highest current environmental early-warning "
                f"indices are {summary}. These values rank weather-related verification "
                "priority; open a district to inspect rainfall, temperature, humidity "
                "and IMD warning drivers."
            )
            outlook_rows = ranked

        payload = self._deterministic(
            intent="forecast_request",
            answer_state="risk_factor_outlook",
            english_answer=english,
            scope=scope,
            reason_codes=[
                "ENVIRONMENTAL_RELATIVE_RISK_INDEX",
                "HUMAN_VERIFICATION_REQUIRED",
                "CALIBRATED_DISEASE_PROBABILITY_REQUIRES_AUTHORISED_SURVEILLANCE",
            ],
            answer_language=answer_language,
            question_language=question_language,
            generation_mode="policy_response",
        )
        payload["outlook"] = {
            "as_of": layer.get("as_of"),
            "quantity": layer.get("quantity"),
            "districts": outlook_rows,
            "is_synthetic": False,
        }
        return payload

    @staticmethod
    def _requested_years(question: str) -> tuple[int, ...]:
        """Four-digit years the question actually names, oldest first."""

        return tuple(
            sorted({int(match) for match in _YEAR_IN_QUESTION.findall(question)})
        )

    @staticmethod
    def _malaria_annual_trend(
        district_id: str | None = None,
        *,
        requested_years: tuple[int, ...] = (),
    ) -> tuple[int, int, int, int, list[dict[str, int]]] | None:
        """Reported-malaria totals per year from the official annual table.

        With ``district_id`` the series is that district's own rows; without it,
        the statewide sum.  A district-scoped question answered from the
        statewide total reads as a district figure and is wrong by two orders of
        magnitude, so the two are never interchanged.

        A question that names years is answered over those years: reporting a
        2010--2024 change to someone who asked about 2015--2024 puts a number
        beside the wrong span.  One named year is a lower bound ("since 2019");
        two or more bound both ends.  A window the table cannot cover falls back
        to the full series rather than to a shorter, silently different one.

        Returns first/last year and total plus the series, or None when the
        bundled panel is unavailable -- the caller then falls back rather than
        inventing a direction of travel.
        """

        try:
            from .public_health import malaria_annual_series, malaria_map
        except Exception:  # noqa: BLE001 - typed public-data fallback
            return None
        try:
            if district_id is None:
                series = malaria_annual_series()
            else:
                series = []
                years = malaria_map(metric="total_cases").get("available_years") or []
                for year in years:
                    rows = malaria_map(year=int(year), metric="total_cases")["records"]
                    row = next(
                        (item for item in rows if item.get("district_id") == district_id),
                        None,
                    )
                    # 2017 and 2018 publish rates without a district case total.
                    # Those years are absent from the series rather than zero.
                    if row is None or row.get("total_cases") is None:
                        continue
                    series.append(
                        {"year": int(year), "total_cases": int(row["total_cases"])}
                    )
        except Exception:  # noqa: BLE001 - typed public-data fallback
            return None
        if len(series) < 2:
            return None
        if requested_years:
            start = min(requested_years)
            end = max(requested_years) if len(requested_years) > 1 else series[-1]["year"]
            window = [row for row in series if start <= int(row["year"]) <= end]
            if len(window) >= 2:
                series = window
        return (
            int(series[0]["year"]),
            int(series[0]["total_cases"]),
            int(series[-1]["year"]),
            int(series[-1]["total_cases"]),
            series,
        )

    def _public_malaria_observation(
        self,
        *,
        scope: dict[str, Any],
        selected_district: str | None,
        selected_disease: str | None,
        answer_language: str,
        question_language: str,
        comparison_districts: list[str] | None = None,
        wants_trend: bool = False,
        wants_ranking: bool = False,
        requested_years: tuple[int, ...] = (),
    ) -> dict[str, Any] | None:
        """Return the latest official annual malaria observation when in scope.

        This does not reinterpret annual NCVBDC values as a current weekly case
        count.  Other diseases continue to require authorised surveillance.

        Two districts produce a comparison, a trend question produces the annual
        series and a ranking question produces the ordered districts, all read
        from the same official table -- the alternative was refusing questions
        the bundled data answers outright.  A trend question that named a
        district gets that district's own series; only an unscoped question gets
        the statewide sum.
        """

        if selected_disease != "malaria":
            return None
        try:
            from .public_health import malaria_map

            layer = malaria_map(metric="total_cases")
        except Exception:  # noqa: BLE001 - typed public-data fallback
            return None
        rows = list(layer.get("records") or [])
        district_row = next(
            (row for row in rows if row.get("district_id") == selected_district),
            None,
        )
        year = int(layer["year"])
        if selected_district and district_row is None:
            return None

        if wants_trend:
            trend = self._malaria_annual_trend(
                selected_district, requested_years=requested_years
            )
            if trend is not None:
                first_year, first_total, last_year, last_total, series = trend
                direction = "fallen" if last_total < first_total else "risen"
                change = abs(last_total - first_total)
                share = (change / first_total * 100) if first_total else 0.0
                if selected_district is not None and district_row is not None:
                    subject = f"{district_row['district_name']}'s"
                    scope_note = (
                        f" These are the {district_row['district_name']} district "
                        "rows only, not an Odisha statewide total."
                    )
                else:
                    subject = "Odisha's statewide"
                    scope_note = ""
                english = (
                    f"Across the bundled official NCVBDC district reports, {subject} "
                    f"reported malaria total has {direction} from {first_total:,} in "
                    f"{first_year} to {last_total:,} in {last_year} — a change of "
                    f"{change:,} ({share:.0f}%), over the {len(series)} years the "
                    f"reports publish a district case total.{scope_note} These are "
                    "annual reported cases/positives from programme reporting, so "
                    "they reflect detection and reporting effort as well as "
                    "transmission, and are not a current-week case count."
                )
                payload = self._deterministic(
                    intent="incidence_request",
                    answer_state="official_annual_observation",
                    english_answer=english,
                    scope=scope,
                    reason_codes=[
                        "OFFICIAL_ANNUAL_NCVBDC_OBSERVATION",
                        "ANNUAL_NOT_CURRENT_WEEK",
                        "REPORTED_NOT_TRUE_INCIDENCE",
                        *(
                            ["DISTRICT_SCOPED_SERIES"]
                            if selected_district is not None
                            else ["STATEWIDE_SCOPED_SERIES"]
                        ),
                    ],
                    answer_language=answer_language,
                    question_language=question_language,
                    generation_mode="policy_response",
                )
                payload["observation"] = {
                    "disease": "malaria",
                    "metric": "total_cases",
                    "geographic_scope": (
                        "district" if selected_district is not None else "state"
                    ),
                    "district_id": selected_district,
                    "series": series,
                    "source_scope": layer.get("source_scope"),
                    "is_synthetic": False,
                }
                return payload

        wanted = [
            identifier
            for identifier in (comparison_districts or [])
            if any(row.get("district_id") == identifier for row in rows)
        ]
        if district_row is None and len(wanted) > 1:
            chosen = [row for row in rows if row["district_id"] in wanted]
            chosen.sort(key=lambda row: int(row["total_cases"]), reverse=True)
            top = chosen[0]
            # One sentence per district. The translator's unit of coherence is the
            # sentence: given all five statistics in one, it dropped brackets and
            # re-paired counts with the wrong district on the way into Hindi.
            # Split this way, each statistic is an independent six-word
            # translation that has nothing to reorder against.
            parts = " ".join(
                f"{row['district_name']} reported {int(row['total_cases']):,} "
                f"cases at an API of {float(row['api']):g}."
                for row in chosen
            )
            english = (
                f"In the bundled official NCVBDC report for {year}, the reported "
                f"totals are as follows. {parts} {top['district_name']} is the "
                "higher of these on reported cases/positives. These are annual "
                "observed statistics, not current-week case counts."
            )
            payload = self._deterministic(
                intent="incidence_request",
                answer_state="official_annual_observation",
                english_answer=english,
                scope=scope,
                reason_codes=[
                    "OFFICIAL_ANNUAL_NCVBDC_OBSERVATION",
                    "ANNUAL_NOT_CURRENT_WEEK",
                ],
                answer_language=answer_language,
                question_language=question_language,
                generation_mode="policy_response",
            )
            payload["observation"] = {
                "disease": "malaria",
                "year": year,
                "metric": "total_cases",
                "records": chosen,
                "source_scope": layer.get("source_scope"),
                "is_synthetic": False,
            }
            payload["citations"] = list(
                dict.fromkeys(str(row["source_url"]) for row in chosen)
            )
            return payload

        # "Which district has the most malaria?" was answered with the statewide
        # sum, which names no district at all.  The official table is ordered and
        # reported instead, with the rate caveat a total invites.
        if district_row is None and wants_ranking:
            ranked = sorted(
                (row for row in rows if row.get("total_cases") is not None),
                key=lambda row: int(row["total_cases"]),
                reverse=True,
            )[:5]
            if ranked:
                parts = " ".join(
                    f"{row['district_name']} reported {int(row['total_cases']):,} "
                    f"cases at an API of {float(row['api']):g}."
                    for row in ranked
                )
                english = (
                    f"In the bundled official NCVBDC report for {year}, the highest "
                    f"reported malaria totals are as follows. {parts} These are annual "
                    "reported cases/positives for the whole district, not current-week "
                    "case counts, and a populous district can report more cases at a "
                    "lower Annual Parasite Incidence than a smaller one."
                )
                payload = self._deterministic(
                    intent="incidence_request",
                    answer_state="official_annual_observation",
                    english_answer=english,
                    scope=scope,
                    reason_codes=[
                        "OFFICIAL_ANNUAL_NCVBDC_OBSERVATION",
                        "ANNUAL_NOT_CURRENT_WEEK",
                        "RANKED_BY_REPORTED_TOTAL_NOT_RATE",
                    ],
                    answer_language=answer_language,
                    question_language=question_language,
                    generation_mode="policy_response",
                )
                payload["observation"] = {
                    "disease": "malaria",
                    "year": year,
                    "metric": "total_cases",
                    "ordering": "reported_total_cases_descending",
                    "records": ranked,
                    "source_scope": layer.get("source_scope"),
                    "is_synthetic": False,
                }
                payload["citations"] = list(
                    dict.fromkeys(str(row["source_url"]) for row in ranked)
                )
                return payload

        if district_row is not None:
            name = str(district_row["district_name"])
            cases = int(district_row["total_cases"])
            api = float(district_row["api"])
            english = (
                f"The latest bundled official NCVBDC district report is for {year}. "
                f"It reports {cases:,} malaria cases/positives for {name}, with an "
                f"Annual Parasite Incidence (API) of {api:g}. This is an annual "
                "observed statistic, not a current-week case count."
            )
            selected_rows = [district_row]
        else:
            cases = sum(int(row["total_cases"]) for row in rows)
            english = (
                f"The latest bundled official NCVBDC district reports are for {year}. "
                f"Across the 30 Odisha district rows they report {cases:,} malaria "
                "cases/positives. This is an annual observed total, not a current-week "
                "case count; district API values should be compared on the map."
            )
            selected_rows = rows
        payload = self._deterministic(
            intent="incidence_request",
            answer_state="official_annual_observation",
            english_answer=english,
            scope=scope,
            reason_codes=["OFFICIAL_ANNUAL_NCVBDC_OBSERVATION", "ANNUAL_NOT_CURRENT_WEEK"],
            answer_language=answer_language,
            question_language=question_language,
            generation_mode="policy_response",
        )
        payload["observation"] = {
            "disease": "malaria",
            "year": year,
            "metric": "total_cases",
            "records": selected_rows,
            "source_scope": layer.get("source_scope"),
            "is_synthetic": False,
        }
        payload["citations"] = list(
            dict.fromkeys(str(row["source_url"]) for row in selected_rows)
        )
        return payload

    def _public_malaria_outlook(
        self,
        *,
        scope: dict[str, Any],
        english_question: str,
        selected_district: str | None,
        answer_language: str,
        question_language: str,
    ) -> dict[str, Any] | None:
        """Render the evaluated 1--3 month public malaria research outlook."""

        try:
            from .public_health import public_outlook_map

            horizon_month = self._public_forecast_horizon_months(english_question)
            layer = public_outlook_map(horizon_month=horizon_month)
        except Exception:  # noqa: BLE001 - current-condition fallback remains available
            return None
        rows = list(layer.get("records") or [])
        district_row = next(
            (row for row in rows if row.get("district_id") == selected_district),
            None,
        )
        if selected_district and district_row is None:
            return None
        target = str(layer["forecast_target"])
        if district_row is not None:
            name = str(district_row["district_name"])
            likelihood = 100.0 * float(district_row["research_indicator_probability"])
            priority = float(district_row["surveillance_priority_score"])
            rain = float(district_row["forecast_precipitation_mean_mm"])
            rain_low = float(district_row["forecast_precipitation_p10_mm"])
            rain_high = float(district_row["forecast_precipitation_p90_mm"])
            temperature = float(district_row["forecast_temperature_mean_c"])
            # Whether the rainfall/temperature block is inside the vector that
            # produced the number, and -- separately -- whether the matched ablation
            # found it worth anything. Both matter: a reader hearing "ECMWF rainfall"
            # beside a percentage will assume the rainfall produced the percentage.
            district_specific = bool(
                district_row.get("environment_used_in_probability")
            )
            environment_earned = bool(layer.get("environment_promoted"))
            if district_specific:
                likelihood_clause = (
                    f"assigns a {likelihood:.1f}% likelihood to its defined HMIS "
                    "indicator"
                )
                driver_clause = (
                    "That figure reads both this district's recent positivity "
                    "history and the seasonal rainfall and temperature outlook."
                    if environment_earned
                    else "That figure is driven by this district's own positivity "
                    "over the preceding three months, measured against its trailing "
                    "75th-percentile bar."
                )
                weather_caveat = (
                    ""
                    if environment_earned
                    else " Removing the weather block from the same model does not "
                    "raise its Brier score, so read the rainfall as context, not as "
                    "the driver of the percentage."
                )
                context_clause = (
                    f"{driver_clause} The ECMWF ensemble projects {rain:.0f} mm "
                    f"precipitation (10th–90th percentile {rain_low:.0f}–"
                    f"{rain_high:.0f} mm) and {temperature:.1f}°C mean temperature "
                    f"over the target window.{weather_caveat}"
                )
            else:
                # The served probability fell back to statewide climatology, so it is
                # identical for all 30 districts. Naming a district beside it read as
                # district-specific, environment-informed risk. It is neither.
                likelihood_clause = (
                    f"assigns a {likelihood:.1f}% statewide calendar-month likelihood "
                    "to its defined HMIS indicator — identical for all 30 districts —"
                )
                context_clause = (
                    f"Only that priority score is specific to {name}. The ECMWF "
                    f"ensemble projects {rain:.0f} mm precipitation (10th–90th "
                    f"percentile {rain_low:.0f}–{rain_high:.0f} mm) and "
                    f"{temperature:.1f}°C mean temperature for {name}; this is shown "
                    "as context and does not enter the likelihood above."
                )
            english = (
                f"For {name}, the {horizon_month}-month public-data research outlook "
                f"{likelihood_clause} and a surveillance-priority score of "
                f"{priority:.1f}/100. {context_clause} This likelihood is for elevated "
                "monthly microscopy positivity—not a calibrated outbreak probability."
            )
            answer_rows = [district_row]
        else:
            # Rank by the model's own probability, not by the burden-weighted
            # priority score. A question about what is *likely* has to be answered
            # with the prediction; the priority score is a planning aid built from
            # last year's official burden and answers a different question.
            scored = [
                row
                for row in rows
                if row.get("research_indicator_probability") is not None
            ]
            ranked = sorted(
                scored,
                key=lambda row: float(row["research_indicator_probability"]),
                reverse=True,
            )[:5]
            summary = ", ".join(
                f"{row['district_name']} "
                f"{100.0 * float(row['research_indicator_probability']):.1f}%"
                for row in ranked
            )
            skill = layer.get("brier_skill_score_vs_unconditional")
            english = (
                f"For the {horizon_month}-month malaria research outlook, the highest "
                f"modelled likelihoods of elevated monthly microscopy positivity are "
                f"{summary}. They come from a rolling-origin backtested model that "
                "reads each district's own recent positivity history alongside the "
                "seasonal rainfall and temperature outlook, and it beats a constant "
                f"base-rate forecast (Brier skill score {skill}). The target is "
                "elevated monthly microscopy positivity—not a calibrated outbreak "
                "probability, and not an operational alert."
            )
            answer_rows = ranked
        payload = self._deterministic(
            intent="forecast_request",
            answer_state="public_research_outlook",
            english_answer=english,
            scope=scope,
            reason_codes=[
                "PUBLIC_HMIS_INDICATOR_TARGET",
                "RESEARCH_OUTLOOK_NOT_OPERATIONAL_ALERT",
                "HUMAN_VERIFICATION_REQUIRED",
            ],
            answer_language=answer_language,
            question_language=question_language,
            generation_mode="policy_response",
        )
        payload["outlook"] = {
            "disease": "malaria",
            "horizon_month": horizon_month,
            "target": target,
            "not_target": layer.get("not_target"),
            "selected_model": layer.get("selected_model"),
            "environment_promoted": layer.get("environment_promoted"),
            "environment_ablation_result": layer.get("environment_ablation_result"),
            "skill_attribution": layer.get("skill_attribution"),
            "brier_skill_score_vs_unconditional": layer.get(
                "brier_skill_score_vs_unconditional"
            ),
            "districts": answer_rows,
            "is_synthetic": False,
        }
        payload["citations"] = list(
            dict.fromkeys(str(row["source_url"]) for row in answer_rows)
        )
        return payload

    @staticmethod
    def _public_forecast_horizon_months(question: str) -> int:
        value = question.casefold()
        if any(term in value for term in ("three month", "3 month", "12 week")):
            return 3
        if any(term in value for term in ("two month", "2 month", "8 week")):
            return 2
        return 1

    @staticmethod
    def _forecast_horizon(question: str) -> int:
        value = question.casefold()
        if any(term in value for term in ("three month", "3 month", "12 week")):
            return 12
        if any(term in value for term in ("two month", "2 month", "8 week")):
            return 8
        if any(term in value for term in ("next month", "one month", "4 week")):
            return 4
        if "2 week" in value or "two week" in value:
            return 2
        return 1

    @staticmethod
    def _district_display(district_id: str) -> str:
        return district_id.removeprefix("OD-DIST-").replace("-", " ").title()

    def _evidence_answer(
        self,
        *,
        question: str,
        english_question: str,
        prior_user_turns: list[str],
        intent: Intent,
        scope: dict[str, Any],
        selected_district: str | None,
        selected_disease: str | None,
        maximum_evidence: int,
        question_language: str,
        answer_language: str,
    ) -> dict[str, Any]:
        fixture_mode = "live_only" if self.database.has_live_signals() else "fixture_only"
        rows = self.database.list_signals(
            district_id=selected_district,
            disease=selected_disease,
            assertion="affirmed",
            fixture_mode=fixture_mode,
            public_only=True,
            limit=max(maximum_evidence * 4, 20),
        )
        if intent == "candidate_alerts":
            rows = [
                row
                for row in rows
                if row["assertion"] == "affirmed"
                and bool(row.get("event_review_eligible"))
                and row.get("review_decision") is None
            ]

        # Rank on a content-bearing passage per row, then re-order the rows to
        # match.  What that passage is built from is reported to the caller: a
        # retrieval state that names the encoder while the corpus is 2,000
        # identical strings claims a capability the deployment does not have.
        records = [
            EvidenceRecord(
                record_id=str(row["id"]),
                text=self._retrieval_text(row),
                metadata=row,
            )
            for row in rows
        ]
        retained = sum(1 for row in rows if self._retained_text(row))
        if rows and retained == len(rows):
            document_basis = "retained_source_text_and_structured_provenance"
        elif retained:
            document_basis = "mixed_retained_source_text_and_structured_provenance"
        else:
            document_basis = "structured_provenance_only_no_retained_source_text"
        retrieval_question = " ".join([*prior_user_turns[-2:], question]).strip()
        ranking = retrieval.rank(
            retrieval_question,
            records,
            top_k=max(maximum_evidence, 1),
            document_basis=document_basis,
        )
        ordered_rows: list[dict[str, Any]] = []
        by_id = {str(row["id"]): row for row in rows}
        for item in ranking.ranked:
            row = by_id.get(item.record.record_id)
            if row is not None:
                ordered_rows.append(row)
        if not ordered_rows:
            ordered_rows = list(rows[:maximum_evidence])
        ordered_rows = ordered_rows[:maximum_evidence]

        prompt_records = self._prompt_records(ranking.ranked[:MAXIMUM_PROMPT_RECORDS])
        contextual_question = english_question
        if prior_user_turns:
            prior_language = route_unicode(prior_user_turns[-1]).value
            if prior_language not in {"en", "hi", "or"}:
                prior_language = "en"
            prior = self._to_english(prior_user_turns[-1], prior_language)
            contextual_question = (
                f"Previous user question: {prior}\nCurrent user question: {english_question}"
            )
        grounded = generation.answer_question(
            contextual_question,
            prompt_records,
            question_language="en",
            target_language=answer_language,
        )

        descriptor = (
            "candidate review signal"
            if intent == "candidate_alerts"
            else "published evidence record"
        )
        summary = (
            f"Found {len(ordered_rows)} {descriptor}(s) in the currently collected "
            f"registered sources ({fixture_mode}). These records are not case counts "
            "and do not prove disease absence when the result is empty."
        )
        answer_state = "records_returned" if ordered_rows else "insufficient_evidence"

        safe_generated = (
            grounded.generation_state == "generated"
            and bool(grounded.answer.strip())
            and grounded.numeric_verification != "unverified_numbers_present"
            and bool(grounded.cited_signal_ids)
        )
        if safe_generated:
            # `grounded.answer_language` is the language actually produced: it
            # falls back to English when a translation was rejected.
            answer_language = grounded.answer_language
            caveat = self._render(NOT_INCIDENCE_CAVEAT, answer_language)
            english_answer = f"{grounded.answer_english} {NOT_INCIDENCE_CAVEAT}".strip()
            answer_text = f"{grounded.answer} {caveat.text}".strip()
        elif grounded.generation_state == "declined_unsupported_by_evidence":
            answer_language = grounded.answer_language
            rendered_summary = self._render(summary, answer_language)
            english_answer = f"{grounded.answer_english} {summary}".strip()
            answer_text = f"{grounded.answer} {rendered_summary.text}".strip()
        else:
            # No generator, a generation failure, a citation-free answer, or an
            # answer containing an unsupported number all fail closed to the
            # reviewed deterministic summary.
            english_answer = summary
            rendered_summary = self._render(summary, answer_language)
            answer_text = rendered_summary.text
            if not rendered_summary.translated:
                answer_language = "en"

        reason_codes = [] if ordered_rows else ["NO_MATCH_IN_CURRENT_SOURCE_COVERAGE"]
        if grounded.generation_state == "declined_unsupported_by_evidence":
            reason_codes = [*reason_codes, "EVIDENCE_DOES_NOT_SUPPORT_ANSWER"]
        if grounded.numeric_verification == "unverified_numbers_present":
            reason_codes = [*reason_codes, "UNVERIFIED_NUMBER_IN_GENERATED_ANSWER"]
        if grounded.generation_state == "generated" and not grounded.cited_signal_ids:
            reason_codes = [*reason_codes, "GENERATED_ANSWER_WITHOUT_CITATION_REJECTED"]

        evidence = [self._evidence_row(row) for row in ordered_rows]
        return {
            "intent": intent,
            "answer_state": answer_state,
            "answer": answer_text,
            "answer_english": english_answer,
            "answer_language": answer_language,
            "question_language": question_language,
            "deterministic_summary": summary,
            "scope": scope,
            "evidence": evidence,
            "citations": list(grounded.cited_signal_ids),
            "reason_codes": reason_codes,
            "is_synthetic": any(item["is_fixture"] for item in evidence),
            "retrieval": ranking.as_dict(),
            "generation": grounded.as_dict(),
            "model": grounded.model if safe_generated else "grounded-summary-rules-v1",
            "generation_mode": "generated" if safe_generated else "retrieval_template",
            "latency_ms": grounded.latency_ms,
            "answer_original": english_answer,
            "generated_answer_rejected": (
                grounded.generation_state == "generated" and not safe_generated
            ),
            "prompt_text_policy": "fixture_text_in_full_live_rows_metadata_only",
            "capabilities": self._capabilities(),
        }

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------
    def _to_english(self, question: str, question_language: str) -> str:
        if question_language == "en":
            return question
        rendered = translation.translate(question, question_language, "en")
        return rendered.text if rendered.state == "translated" else question

    def _render(self, english: str, answer_language: str) -> translation.TranslationResult:
        if answer_language == "en":
            return translation.TranslationResult(
                text=english,
                source_language="en",
                target_language="en",
                state="identity",
                engine="none",
            )
        return translation.translate(
            english,
            "en",
            answer_language,
            glossary=district_terms("en", answer_language),
        )

    def _deterministic(
        self,
        *,
        intent: Intent,
        answer_state: str,
        english_answer: str,
        scope: dict[str, Any],
        reason_codes: list[str],
        answer_language: str,
        question_language: str,
        extra: dict[str, Any] | None = None,
        generation_mode: Literal["refusal", "policy_response"] = "refusal",
    ) -> dict[str, Any]:
        """A reviewed, policy-fixed answer, rendered in the caller's language."""

        rendered = self._render(english_answer, answer_language)
        payload: dict[str, Any] = {
            "intent": intent,
            "answer_state": answer_state,
            "answer": rendered.text,
            "answer_english": english_answer,
            "answer_language": answer_language if rendered.translated else "en",
            "question_language": question_language,
            "scope": scope,
            "evidence": [],
            "citations": [],
            "reason_codes": reason_codes,
            "is_synthetic": False,
            "answer_origin": "deterministic_policy_text",
            "model": "policy-rules-v1",
            "generation_mode": generation_mode,
            "latency_ms": 0,
            "translation": rendered.as_dict(),
            "capabilities": self._capabilities(),
        }
        if extra:
            payload.update(extra)
        return payload

    @staticmethod
    def _capabilities() -> dict[str, Any]:
        return {
            "translation": translation.available(),
            "semantic_retrieval": retrieval.available(),
            "generative_answer": generation.available(),
            "mode": nlp_models.nlp_mode(),
        }

    @staticmethod
    def _retained_text(row: dict[str, Any]) -> str:
        """The stored evidence span, empty when the row retained no source text."""

        text = str(row.get("evidence_text") or "").strip()
        return "" if not text or text == LIVE_EVIDENCE_PLACEHOLDER else text

    @staticmethod
    def _retrieval_text(row: dict[str, Any]) -> str:
        """The passage embedded for retrieval.

        Live rows retain no source text: ``evidence_text`` is one fixed
        placeholder string on every one of them, so embedding it handed the
        encoder thousands of identical passages, and a cross-lingual model that
        ranks identical strings ranks nothing.  What each row does carry is
        structured provenance -- disease, district, the registered document
        title, language and retrieval date -- none of which is crawled free
        text.  That is written out as a short passage, with the district named
        in all three scripts so an Odia or Hindi question reaches the same
        record an English one does.  Retained fixture text is appended in full.
        """

        disease = str(row.get("disease") or "").replace("_", " ").strip()
        district_id = str(row.get("district_id") or "")
        names = (
            [district_display_name(district_id, code) for code in ("en", "or", "hi")]
            if district_id
            else []
        )
        district = ", ".join(dict.fromkeys(name for name in names if name))
        language = _LANGUAGE_NAMES.get(str(row.get("language") or ""), "unspecified")
        title = _source_titles().get(str(row.get("source_id") or ""), "")
        retrieved = str(row.get("retrieved_at") or "")[:10]
        parts = [
            f"{disease.capitalize() or 'Health topic'} mentioned for "
            f"{district or 'an unresolved district'}, Odisha, India."
        ]
        parts.append(
            f"{language}-language published document: {title}."
            if title
            else f"{language}-language published document."
        )
        if retrieved:
            parts.append(f"Retrieved {retrieved}.")
        retained = EvidenceAgent._retained_text(row)
        if retained:
            parts.append(retained)
        return " ".join(parts)

    @staticmethod
    def _prompt_records(ranked: tuple[RankedRecord, ...]) -> list[RankedRecord]:
        """Fixture text goes into the prompt in full; live rows contribute metadata only."""

        prepared: list[RankedRecord] = []
        for item in ranked:
            row = dict(item.record.metadata)
            if bool(row.get("is_fixture")):
                text = str(row.get("evidence_text") or "").strip()
            else:
                # State the publication fact first. This provenance IS the evidence
                # for this product -- the platform's claim is a count of what was
                # published, not a reading of what the article said. Leading with the
                # withholding caused the model to read a populated record as an empty
                # one and decline questions the metadata fully answers.
                # Facts only. Anything imperative here would land inside the block
                # the model is told never to take instructions from, so constraints
                # belong in the system prompt, not in a record.
                district = str(row.get("district_id") or "").removeprefix("OD-DIST-")
                retrieved = str(row.get("retrieved_at") or "")[:10]
                text = (
                    f"Published mention of {row.get('disease')} for district "
                    f"{district.replace('-', ' ').title() or 'unresolved'}, in a "
                    f"{row.get('language') or 'unknown'}-language document from source "
                    f"{row.get('source_id')}, retrieved {retrieved}."
                )
            prepared.append(
                RankedRecord(
                    record=EvidenceRecord(
                        record_id=item.record.record_id,
                        text=text,
                        metadata=row,
                    ),
                    score=item.score,
                    rank=item.rank,
                )
            )
        return prepared

    @staticmethod
    def _carries_intent_terms(question: str) -> bool:
        """True when the question states an intent rather than only a scope."""

        value = question.casefold()
        return any(term in value for term in INTENT_TERMS)

    def _place_outside_odisha(self, question: str, english_question: str) -> str | None:
        """A capitalised place in the question that is not an Odisha district.

        Only called once the gazetteer has failed on the whole question, so a
        surviving candidate is a place this platform holds no records for.  Names
        the platform uses itself (Odisha, IDSP, HMIS) and disease names are
        excluded, as is anything the gazetteer or disease lexicon can resolve on
        its own -- a false positive here refuses a valid Odisha question.
        """

        for text in dict.fromkeys((question, english_question)):
            for match in _PLACE_PHRASE.finditer(text):
                raw = (match.group(1) or match.group(2) or "").strip()
                # "Puri District" is Puri; "Which district" is nothing at all.
                words = [
                    word for word in raw.split() if word.casefold() not in _NOT_A_PLACE
                ]
                candidate = " ".join(words)
                if not candidate:
                    continue
                if self.gazetteer.resolve(candidate) or self.diseases.find(candidate):
                    continue
                return candidate
        return None

    @staticmethod
    def _intent(question: str, *, has_disease: bool = False) -> Intent:
        if any(term in question for term in CLINICAL_ADVICE_TERMS):
            return "clinical_advice_request"
        # EpiClim is a named, frozen data audit.  A question asking whether
        # that catalogue can train a forecast must return the reproduced audit
        # findings, rather than being swallowed by the generic forecast route.
        if "epiclim" in question:
            return "data_audit"
        if (
            any(term in question for term in FORECAST_TERMS)
            or (has_disease and any(term in question for term in OUTLOOK_TERMS))
            or (
                any(term in question for term in FUTURE_TERMS)
                and (has_disease or any(term in question for term in OUTBREAK_TERMS))
            )
        ):
            return "forecast_request"
        if (
            any(term in question for term in INCIDENCE_TERMS)
            or ("how many" in question and "case" in question)
            # A comparison needs an explicit counted quantity, because "compare
            # dengue evidence in Ganjam and Khordha" is about published records
            # and must stay on the evidence path rather than be answered from a
            # statistics table.
            or (
                has_disease
                and any(term in question for term in COMPARISON_TERMS)
                and any(term in question for term in STATISTIC_NOUNS)
                and not any(term in question for term in EVIDENCE_NOUNS)
            )
            # A trend or a distribution needs no such noun: in "has malaria gone
            # up since 2010" and "show the malaria heatmap" the disease name is
            # itself the quantity. Only the evidence vocabulary pulls these back
            # to the media path.
            or (
                has_disease
                and any(
                    term in question for term in (*TREND_TERMS, *DISTRIBUTION_TERMS)
                )
                and not any(term in question for term in EVIDENCE_NOUNS)
            )
        ):
            return "incidence_request"
        if any(term in question for term in AUDIT_TERMS):
            return "data_audit"
        if any(term in question for term in VERIFIED_TERMS):
            return "verified_events"
        if any(term in question for term in ALERT_TERMS):
            return "candidate_alerts"
        return "evidence_search"

    @staticmethod
    def _evidence_row(row: dict[str, Any]) -> dict[str, Any]:
        is_fixture = bool(row.get("is_fixture"))
        return {
            "signal_id": row["id"],
            "source_id": row["source_id"],
            "source_snapshot_id": row["source_snapshot_id"],
            "district_id": row["district_id"],
            "disease": row["disease"],
            "assertion": row["assertion"],
            # Synthetic evidence is inspectable. Live text is never retained
            # while multilingual PERSON redaction recall is unvalidated.
            "redacted_evidence": (row["evidence_text"] if is_fixture else None),
            "evidence_visibility": (
                "synthetic_fixture" if is_fixture else LIVE_EVIDENCE_REDACTION_STATE
            ),
            "retrieved_at": row["retrieved_at"],
            "content_sha256": row["content_sha256"],
            "canonical_url": row.get("registered_source_url"),
            "canonical_url_state": "registered_source_only_detail_url_withheld",
            "access_path": row.get("access_path"),
            "review_state": row.get("review_task_state"),
            "review_decision": row.get("review_decision"),
            "is_fixture": is_fixture,
            "is_synthetic": is_fixture,
            "language": row.get("language"),
            "processing_state": row.get("processing_state"),
            "redaction_state": row.get("redaction_state"),
            "event_review_eligible": bool(row.get("event_review_eligible")),
            "extractor_version": row.get("extractor_version"),
        }
