#!/usr/bin/env python3
"""Write machine-readable evidence after the Make verification chain succeeds."""

from __future__ import annotations

import csv
import hashlib
import json
import os
import re
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_tree_sha256() -> str:
    digest = hashlib.sha256()
    roots = [
        "packages",
        "services",
        "workers",
        "pipelines",
        "scripts",
        "tests",
        "config",
        "apps/web/src",
        "apps/web/public",
        ".github/workflows",
    ]
    files: list[Path] = []
    for relative in roots:
        files.extend(
            path
            for path in (ROOT / relative).rglob("*")
            if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"
        )
    files.extend(
        ROOT / name
        for name in (
            "pyproject.toml",
            "uv.lock",
            "Makefile",
            "Dockerfile",
            "Dockerfile.local",
            "Caddyfile.huggingface",
            "docker-compose.yml",
            ".dockerignore",
            ".gitignore",
            ".env.example",
            "README.md",
            "SOURCES.md",
            "SECURITY.md",
            "NOTICE.md",
            "apps/web/package.json",
            "apps/web/package-lock.json",
            "apps/web/vite.config.ts",
        )
    )
    for path in sorted(files):
        relative_bytes = path.relative_to(ROOT).as_posix().encode()
        digest.update(len(relative_bytes).to_bytes(4, "big"))
        digest.update(relative_bytes)
        body = path.read_bytes()
        digest.update(len(body).to_bytes(8, "big"))
        digest.update(body)
    return digest.hexdigest()


def main() -> None:
    prerequisite_receipt = os.getenv("ACCEPTANCE_PREREQUISITES", "")
    expected_prerequisites = "doctor,seed,ruff,mypy,pytest,web-build"
    if prerequisite_receipt != expected_prerequisites:
        raise SystemExit(
            "acceptance report must be generated by `make verify` after all prerequisites"
        )
    boundary_manifest = json.loads(
        (ROOT / "data" / "boundaries" / "manifest.json").read_text()
    )
    boundary_path = ROOT / "data" / "boundaries" / boundary_manifest["asset"]
    boundary = json.loads(boundary_path.read_text())
    epiclim = json.loads((ROOT / "data" / "epiclim" / "audit.json").read_text())
    fixture_manifest_path = ROOT / "tests" / "fixtures" / "manifest.json"
    fixtures = json.loads(fixture_manifest_path.read_text())
    for relative, expected in {**fixtures["documents"], **fixtures["environment"]}.items():
        actual = sha256(ROOT / "tests" / "fixtures" / relative)
        if actual != expected:
            raise SystemExit(f"fixture checksum failed: {relative}")
    forecast = json.loads(
        (ROOT / "data" / "synthetic" / "forecast_report.json").read_text()
    )
    with (ROOT / "data" / "public_health" / "ncvbdc_malaria_annual.csv").open(
        encoding="utf-8", newline=""
    ) as handle:
        ncvbdc_rows = list(csv.DictReader(handle))
    with (ROOT / "data" / "public_health" / "hmis_district_monthly.csv").open(
        encoding="utf-8", newline=""
    ) as handle:
        hmis_rows = list(csv.DictReader(handle))
    seasonal = json.loads(
        (ROOT / "data" / "environment" / "seasonal_outlook.json").read_text()
    )
    public_model = json.loads(
        (ROOT / "data" / "forecasting" / "public_hmis_malaria_model.json").read_text()
    )
    sources = json.loads((ROOT / "config" / "sources.yaml").read_text())["sources"]
    workflow_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    )
    action_references = re.findall(r"uses:\s*([^\s#]+)", workflow_text)
    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    dockerignore = (ROOT / ".dockerignore").read_text(encoding="utf-8").splitlines()
    database_source = (ROOT / "services" / "api" / "database.py").read_text(
        encoding="utf-8"
    )
    checks = {
        "boundary_checksum": sha256(boundary_path) == boundary_manifest["asset_sha256"],
        "boundary_feature_count": len(boundary["features"]) == 30,
        "boundary_ids_unique": len(
            {feature["properties"]["district_id"] for feature in boundary["features"]}
        )
        == 30,
        "epiclim_odisha_rows": epiclim["odisha"]["rows"] == 358,
        "epiclim_dengue_rows": epiclim["odisha"]["disease_counts"]["Dengue"] == 2,
        "epiclim_forecast_refused": (
            epiclim["eligibility"]["district_week_count_forecast"] == "ineligible"
        ),
        "fixture_document_count": len(fixtures["documents"]) == 12,
        "synthetic_watermark": (
            forecast["watermark"] == "SIMULATION_ONLY_NOT_ODISHA_RISK"
        ),
        "real_odisha_prediction_absent": (
            forecast["real_odisha_prediction_available"] is False
        ),
        "synthetic_payload_flag": forecast["is_synthetic"] is True,
        "official_malaria_panel": len(ncvbdc_rows) == 450
        and len(
            {
                row["district_id"]
                for row in ncvbdc_rows
                if row["year"] == "2024"
            }
        )
        == 30
        and sum(
            int(row["total_cases"])
            for row in ncvbdc_rows
            if row["year"] == "2024" and row["total_cases"]
        )
        == 68_693,
        "public_hmis_panel": len(hmis_rows) == 2_880
        and len({row["period_start"] for row in hmis_rows}) == 96,
        "seasonal_ensemble_outlook": seasonal["ensemble_members"] == 51
        and len(seasonal["districts"]) == 30
        and all(len(row["windows"]) == 3 for row in seasonal["districts"]),
        "public_outlook_rolling_origin_evaluated": public_model["modeling_rows"] == 1_936
        and len(public_model["folds"]) == 3
        # The ladder must be scored against the null competitor (a constant equal to
        # the training base rate) and must report its skill honestly. Asserting a
        # particular winner would reward whichever model happened to win; asserting
        # that the comparison exists and is published is the durable check.
        and "unconditional_climatology" in public_model["pooled"]
        and public_model["ridge_beats_baseline"]
        == (
            public_model["pooled"]["ridge_logistic"]["brier"]
            < public_model["pooled"]["calendar_month_baseline"]["brier"]
        )
        and isinstance(public_model["beats_unconditional_climatology"], bool)
        and public_model["selected_by_brier"]
        == min(
            public_model["pooled"], key=lambda name: public_model["pooled"][name]["brier"]
        ),
        # The environment ablation must remove exactly one feature block. Comparing
        # the full model against season-only would drop the lagged-disease block at
        # the same time and credit rainfall with the history block's contribution.
        "environment_ablation_is_matched": (
            set(public_model["environment_block_ablation"]["with_environment"]["features"])
            - set(
                public_model["environment_block_ablation"]["without_environment"][
                    "features"
                ]
            )
            == set(public_model["environment_block_ablation"]["removed_features"])
        ),
        # The lagged-disease block is what carries objective 3. Its value is the
        # published skill against the null competitor, so the gate is that the
        # comparison ran and its verdict agrees with the scores.
        "predictive_skill_published": public_model["beats_unconditional_climatology"]
        == (
            public_model["pooled"][public_model["selected_by_brier"]]["brier"]
            < public_model["pooled"]["unconditional_climatology"]["brier"]
        )
        and isinstance(public_model["brier_skill_score_vs_unconditional"], int | float),
        "registered_source_routes": len(sources) >= 100,
        "enabled_source_routes": sum(bool(source["enabled"]) for source in sources) >= 20,
        # Objective 1 names three languages; each must have live enabled routes.
        "trilingual_enabled_routes": all(
            any(
                language in source["languages"]
                for source in sources
                if source["enabled"]
            )
            for language in ("en", "hi", "or")
        ),
        # Hindi coverage used to be the weak leg: the registry carried national
        # reference pages whose Hindi body was navigation text, so the gate asserted
        # that no route CLAIMED Odisha incident coverage. The registry now carries
        # Odisha-scoped Hindi news desks, so the honest assertion inverts -- Hindi
        # must reach Odisha specifically, not merely exist as a national page.
        "hindi_routes_include_odisha_scoped": sum(
            1
            for source in sources
            if source["enabled"]
            and "hi" in source["languages"]
            and "odisha" in source["id"]
        )
        >= 1,
        "separate_hindi_route": any(
            source["id"] == "newsonair_odisha_dengue_hi"
            and source["languages"] == ["hi"]
            and source["enabled"] is False
            and source["rights_state"]
            == "prior_written_nsd_air_permission_required"
            for source in sources
        ),
        # Every route that is disabled must say why, so a reader can tell a rights
        # or availability decision from an unexplained gap.
        "disabled_routes_state_a_reason": all(
            str(source.get("disabled_reason") or source.get("policy_state") or "").strip()
            for source in sources
            if not source["enabled"]
        ),
        "web_build": (ROOT / "apps" / "web" / "dist" / "index.html").is_file(),
        "web_sourcemaps_absent": not any(
            (ROOT / "apps" / "web" / "dist").rglob("*.map")
        ),
        "web_security_headers_present": all(
            header
            in (ROOT / "apps" / "web" / "public" / "_headers").read_text(
                encoding="utf-8"
            )
            for header in ("Content-Security-Policy", "Strict-Transport-Security")
        ),
        "live_text_non_retention_enforced": all(
            token in database_source
            for token in (
                "LIVE_EVIDENCE_PLACEHOLDER",
                "LIVE_EVIDENCE_REDACTION_STATE",
                "content_not_retained_unvalidated_pii",
            )
        ),
        "remote_postgres_identity_verification_enforced": all(
            token in database_source for token in ("sslmode=verify-full", "sslrootcert=system")
        ),
        "github_actions_immutable": bool(action_references)
        and all(
            re.fullmatch(r"[^@\s]+@[0-9a-f]{40}", reference)
            for reference in action_references
        ),
        "docker_bootstrap_immutable": dockerfile.count("@sha256:") >= 2
        and "pip install" not in dockerfile,
        "raw_and_quarantine_excluded_from_image": all(
            item in dockerignore for item in ("data/raw/", "data/quarantine/")
        ),
        "software_licence": (ROOT / "LICENSE").is_file(),
    }
    if not all(checks.values()):
        failed = sorted(key for key, passed in checks.items() if not passed)
        raise SystemExit(f"acceptance evidence failed: {failed}")
    report = {
        "schema_version": "1.0.0",
        "generated_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "deployment_profile": "production_shaped",
        "revision": os.getenv("GITHUB_SHA", "working-tree"),
        "source_tree_sha256": source_tree_sha256(),
        "dependency_lock_sha256": {
            "uv.lock": sha256(ROOT / "uv.lock"),
            "apps/web/package-lock.json": sha256(ROOT / "apps/web" / "package-lock.json"),
        },
        "status": "pass",
        "verification_chain": ["doctor", "seed", "ruff", "mypy", "pytest", "web-build"],
        "prerequisite_receipt": prerequisite_receipt,
        "invocation_contract": (
            "This report is written only after every Make verify prerequisite succeeds."
        ),
        "checks": checks,
        "known_non_claims": [
            "no_authorised_operational_odisha_outbreak_probability",
            "public_research_likelihood_targets_hmis_indicator_not_outbreak",
            "public_source_density_is_not_incidence",
            "component_accuracy_unvalidated_on_target_corpus",
            "live_source_text_not_retained_until_pii_redaction_is_validated",
            "source_coverage_is_a_registered_allowlist_not_complete_internet_recall",
            "not_enterprise_operational_or_safe_to_host_certified",
        ],
        "asset_digests": {
            "boundary": boundary_manifest["asset_sha256"],
            "fixture_manifest": sha256(fixture_manifest_path),
            "epiclim_audit": sha256(ROOT / "data" / "epiclim" / "audit.json"),
            "synthetic_forecast": sha256(
                ROOT / "data" / "synthetic" / "forecast_report.json"
            ),
            "official_malaria_panel": sha256(
                ROOT / "data" / "public_health" / "ncvbdc_malaria_annual.csv"
            ),
            "public_hmis_panel": sha256(
                ROOT / "data" / "public_health" / "hmis_district_monthly.csv"
            ),
            "seasonal_outlook": sha256(
                ROOT / "data" / "environment" / "seasonal_outlook.json"
            ),
            "public_hmis_model": sha256(
                ROOT / "data" / "forecasting" / "public_hmis_malaria_model.json"
            ),
        },
    }
    output = ROOT / "reports" / "acceptance.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"acceptance_report={output}")


if __name__ == "__main__":
    main()
